#!/usr/bin/env python3
"""
Parse .config file and generate C header file
For AISafe64 menuconfig system
AI-Generated, Safety-Certifiable, Native 64-bit RTOS
"""

import sys
import re
from typing import Dict


def parse_config(config_file: str) -> Dict[str, str]:
    """
    Parse .config file and return configuration dictionary

    Args:
        config_file: Path to .config file

    Returns:
        Dictionary mapping config names to values
    """
    configs = {}

    try:
        with open(config_file, 'r') as f:
            for line in f:
                line = line.strip()

                # Skip empty lines and comments
                if not line or line.startswith('#'):
                    continue

                # Parse CONFIG_XXX=value
                match = re.match(r'CONFIG_([^=]+)=(.+)', line)
                if match:
                    name = match.group(1)
                    value = match.group(2)

                    # Convert boolean values
                    if value == 'y':
                        value = '1'
                    elif value == 'n':
                        value = '0'
                    elif value == 'm':
                        value = '2'

                    configs[name] = value

    except FileNotFoundError:
        print(f"Error: Config file '{config_file}' not found", file=sys.stderr)
        sys.exit(1)

    return configs


def generate_header(configs: Dict[str, str], output_file: str) -> None:
    """
    Generate C header file from configuration dictionary

    Args:
        configs: Configuration dictionary
        output_file: Path to output header file
    """
    try:
        with open(output_file, 'w') as f:
            # File header
            f.write("/** @file autoconf.h\n")
            f.write(" * @brief Auto-generated configuration header for AISafe64\n")
            f.write(" * @warning DO NOT EDIT - Generated by menuconfig\n")
            f.write(" */\n\n")

            f.write("#ifndef AUTOCONF_H\n")
            f.write("#define AUTOCONF_H\n\n")

            f.write("/* AISafe64 Configuration Settings */\n")
            f.write("/* AI-Generated, Safety-Certifiable, Native 64-bit RTOS */\n\n")

            # Generate #define statements
            for name, value in sorted(configs.items()):
                # Numeric values
                if re.match(r'^\d+$', value):
                    f.write(f"#define CONFIG_{name} {value}U\n")
                # Hex values
                elif re.match(r'^0x[0-9a-fA-F]+$', value):
                    f.write(f"#define CONFIG_{name} {value}UL\n")
                # String values
                elif value.startswith('"'):
                    f.write(f"#define CONFIG_{name} {value}\n")
                # Other values
                else:
                    f.write(f"#define CONFIG_{name} {value}\n")

            f.write("\n#endif /* AUTOCONF_H */\n")

    except IOError as e:
        print(f"Error: Failed to write output file: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    """Main function"""
    if len(sys.argv) != 3:
        print("Usage: parse_config.py <.config> <autoconf.h>")
        print("\nExample:")
        print("  python3 parse_config.py .config include/generated/autoconf.h")
        sys.exit(1)

    config_file = sys.argv[1]
    output_file = sys.argv[2]

    # Parse configuration
    configs = parse_config(config_file)

    if not configs:
        print("Warning: No configuration items found", file=sys.stderr)
        sys.exit(1)

    # Generate header file
    generate_header(configs, output_file)

    print(f"Generated {output_file} with {len(configs)} configuration items")


if __name__ == '__main__':
    main()
